### ISSUE TITLE
Build problems - C++ error C2039 and warning C4047 found in to v3.0.1663 (8be2c5fd) 

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#60]
Version: 3.0.1663 (8be2c5fd) [master]

// Solution Plugins-Extra VC++2017 console log

> Building Extra-Plugins        [ERROR] .\trunk\plugins-extra\securityexplorerplugin\explorer.c(583): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplu gin\sessions.c(115): error C2039: OpenObject: is not a member"_PH_STD_OBJECT _SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(128): warning C4047: function: "PWSTR"differs by levels of indirect treatment from"NTSTATUS (__stdcall *)(PSECURITY_DESCRIPTOR *,SECURITY_INFORMATION,PVOID)" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(128): warning C4024: PhEditSecurity:different types for formal and actual parameters3 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(592): warning C4047: function: "PWSTR"differs by levels of indirect treatment from"NTSTATUS (__stdcall *)(PSECURITY_DESCRIPTOR *,SECURITY_INFORMATION,PVOID)" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(130): warning C4047: function: "PPH_CLOSE_OBJECT"differs by levels of indirect treatment from"PH_STD_OBJECT_SECURITY *" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplu gin\explorer.c(592): warning C4024: PhEditSecurity:different types for formal and actual parameters3 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(130): warning C4024: PhEditSecurity:different types for formal and actual parameters5 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(594): warning C4047: function: "PPH_CLOSE_OBJECT"differs by levels of indirect treatment from"PH_STD_OBJECT_SECURITY *" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(133): warning C4020: PhEditSecurity:too many actual parameters[.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(594): warning C4024: PhEditSecurity:different types for formal and actual parameters5 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(597): warning C4020: PhEditSecurity:too many actual parameters[.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(651): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(664): warning C4047: function: "PWSTR"differs by levels of indirect treatment from"NTSTATUS (__stdcall *)(PSECURITY_DESCRIPTOR *,SECURITY_INFORMATION,PVOID)" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(664): warning C4024: PhEditSecurity:different types for formal and actual parameters3 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(666): warning C4047: function: "PPH_CLOSE_OBJECT"differs by levels of indirect treatment from"PH_STD_OBJECT_SECURITY *" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(666): warning C4024: PhEditSecurity:different types for formal and actual parameters5 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(669): warning C4020: PhEditSecurity:too many actual parameters[.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(115): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(128): warning C4047: function: "PWSTR"differs by levels of indirect treatment from"NTSTATUS (__stdcall *)(PSECURITY_DESCRIPTOR *,SECURITY_INFORMATION,PVOID)" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(128): warning C4024: PhEditSecurity:different types for formal and actual parameters3 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(130): warning C4047: function: "PPH_CLOSE_OBJECT"differs by levels of indirect treatment from"PH_STD_OBJECT_SECURITY *" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(130): warning C4024: PhEditSecurity:different types for formal and actual parameters5 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(133): warning C4020: PhEditSecurity:too many actual parameters[.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\support.c(162): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\support.c(198): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\support.c(251): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\support.c(276): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(583): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(592): warning C4047: function: "PWSTR"differs by levels of indirect treatment from"NTSTATUS (__cdecl *)(PSECURITY_DESCRIPTOR *,SECURITY_INFORMATION,PVOID)" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(592): warning C4024: PhEditSecurity:different types for formal and actual parameters3 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(594): warning C4047: function: "PPH_CLOSE_OBJECT"differs by levels of indirect treatment from"PH_STD_OBJECT_SECURITY *" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(594): warning C4024: PhEditSecurity:different types for formal and actual parameters5 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(597): warning C4020: PhEditSecurity:too many actual parameters[.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(651): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(664): warning C4047: function: "PWSTR"differs by levels of indirect treatment from"NTSTATUS (__cdecl *)(PSECURITY_DESCRIPTOR *,SECURITY_INFORMATION,PVOID)" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(664): warning C4024: PhEditSecurity:different types for formal and actual parameters3 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(666): warning C4047: function: "PPH_CLOSE_OBJECT"differs by levels of indirect treatment from"PH_STD_OBJECT_SECURITY *" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(666): warning C4024: PhEditSecurity:different types for formal and actual parameters5 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\explorer.c(669): warning C4020: PhEditSecurity:too many actual parameters[.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(115): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(128): warning C4047: function: "PWSTR"differs by levels of indirect treatment from"NTSTATUS (__cdecl *)(PSECURITY_DESCRIPTOR *,SECURITY_INFORMATION,PVOID)" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(128): warning C4024: PhEditSecurity:different types for formal and actual parameters3 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(130): warning C4047: function: "PPH_CLOSE_OBJECT"differs by levels of indirect treatment from"PH_STD_OBJECT_SECURITY *" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(130): warning C4024: PhEditSecurity:different types for formal and actual parameters5 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\sessions.c(133): warning C4020: PhEditSecurity:too many actual parameters[.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\support.c(162): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\support.c(198): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\support.c(251): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\support.c(276): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(115): error C2039: OpenObject: is not a member"_PH_STD_OBJECT_SECURITY" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(128): warning C4047: function: "PWSTR"differs by levels of indirect treatment from"NTSTATUS (__cdecl *)(PSECURITY_DESCRIPTOR *,SECURITY_INFORMATION,PVOID)" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(128): warning C4024: PhEditSecurity:different types for formal and actual parameters3 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(130): warning C4047: function: "PPH_CLOSE_OBJECT"differs by levels of indirect treatment from"PH_STD_OBJECT_SECURITY *" [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(130): warning C4024: PhEditSecurity:different types for formal and actual parameters5 [.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]
> .\trunk\plugins-extra\securityexplorerplugin\users.c(133): warning C4020: PhEditSecurity:too many actual parameters[.\trunk\plugins-extra\SecurityExplorerPlugin\SecurityExplorer.vcxproj]. .
> 

Plug-in Security Explorer can't build in to 3.0.6190.1663 Git-8be2c5fd (I not found SecurityExplorer.dll and SecurityExplorer.pdb files in to compiler output directory).

**Comment by dmex** [comment]
We already get build warnings from appveyor:
https://ci.appveyor.com/project/processhacker/processhacker

You don't need to create a bug ticket every time the repo doesn't compile.

**Comment by VictorVG** [comment]
![1](https://user-images.githubusercontent.com/906886/42922925-981b623a-8b2b-11e8-8fdf-03500a235afa.png)

**Comment by VictorVG** [comment]
[v3.0.6225.1698 Git-5ffb532d build logs.zip](https://github.com/processhacker/plugins-extra/files/2223398/v3.0.6225.1698.Git-5ffb532d.build.logs.zip)

**Comment by VictorVG** [comment]
**v3.0.6257.1730 Git-ed6ab455**

![ph v3 0 6257 1730 git-ed6ab455](https://user-images.githubusercontent.com/906886/43182351-ba25d884-8fe9-11e8-80ba-7a96b31c213c.png)

AvgCpuPlugin.dll
DnsCachePlugin.dll
FirewallMonitorPlugin.dll
NvGpuPlugin.dll
PerfMonPlugin.dll
PoolMonPlugin.dll
SecurityExplorer.dll
TaskbarExtPlugin.dll

don't builds ....

**Comment by VictorVG** [comment]
Version: 3.0.1740 (ce7326cb) [master] plugins AvgCpuPlugin, DnsCachePlugin, FirewallMonitorPlugin, 
NvGpuPlugin, PerfMonPlugin, PoolMonPlugin, SecurityExplorer and TaskbarExtPlugin also can't build, and  AvgCpuPlugin, DnsCachePlugin, FirewallMonitorPlugin, NvGpuPlugin, PerfMonPlugin, PoolMonPlugin and TaskbarExtPlugin don't load then incompatible this new version.
